### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by arusso1290** [adlnet-archive/warriorAthlete#1]
I want to use [Sourcegraph](https://sourcegraph.com) for warriorAthlete code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/adlnet/warriorAthlete. (It should only take 30 seconds.)

Thank you!

**Comment by stevenvergenz** [comment]
Forgive me for being suspicious, but this message looks awfully like spam. Tell me, what is Sourcegraph, and what's your favorite color?

**Comment by arusso1290** [comment]
Source Graph is a tool for intelligent code collaboration. My favorite color is blue

Andrea

**Comment by stevenvergenz** [comment]
Which smells worse, a barnyard or a hospital?

**Comment by arusso1290** [comment]
barnyard

**Comment by stevenvergenz** [comment]
Well, I'm convinced you're a human now :)

We'll look into this Source Graph, and if we decide it's valuable we'll get it integrated. Thanks for the suggestion.
